### ISSUE TITLE
Im blind plz dark

### ISSUE THREAD

**Issue by jacobtread** [Fallstop/HCNoticeReader#1]
Plz add dark theme

**Comment by jacobtread** [comment]
Brr add the following to their respective selectors for simple darkmode
```css
main.svelte-1c1p02y .PrimaryContent.svelte-1c1p02y {
      background-color: #444;
}

body {
   background: #333;
    color: #999;
}
```
